### ISSUE TITLE
Openwrt官方源码更新后无法云编译

### ISSUE THREAD

**Issue by veik** [CTCD/build-openwrt#1]
cat config.buildinfo >>openwrt/.config && cat openwrt/.config
  echo "DEVICE_NAME=${DEVICE_NAME}" >> $GITHUB_ENV
  shell: /usr/bin/bash -e {0}
sed: can't read openwrt/package/network/config/wifi-scripts/files/lib/wifi/mac80211.sh: No such file or directory
Error: Process completed with exit code 2.

**Comment by CTCD** [comment]
最新提交已修复 请更新
